### ISSUE TITLE
Create database

### ISSUE THREAD

**Issue by gillkashdeep** [gillkashdeep/COMP313-002-TEAM6#1]

**Comment by manmeetkaur729** [comment]
Kash i am trying to explore about it if i get any info i ll let u know...

**Comment by gillkashdeep** [comment]
Thanks manmeet I am working on Schedule feature. And the new stories I will find a give you an update.


________________________________

**Comment by manmeetkaur729** [comment]
I have start looking for feature of language.. hope to come out with a solution soon

**Comment by divyathakkar1417** [comment]
The database was successfully created.
