### ISSUE TITLE
New functionality ideas

### ISSUE THREAD

**Issue by manmeetkaur729** [gillkashdeep/COMP313-002-TEAM6#3]
Team please come with new ideas that we can implement along with demo of code so that we can use that code and help kash to integrate it with already working app

**Comment by Rajwinder130197** [comment]
we can support an app in multiple languages so user who does not know English he can choose his native language

**Comment by Rajwinder130197** [comment]
and we can also add functionality of sharing our app.

**Comment by gillkashdeep** [comment]
The conversion of temperature is implemented.

**Comment by manmeetkaur729** [comment]
thats wonderful kash..

**Comment by manmeetkaur729** [comment]
me and rajwinder is working on design part of all this suggested notification... will send you by 2 hours max...as it is going to be complete.. so we will add all the icons and labels for the above suggested features and would see which one would be done this time and rest we will use in next release

**Comment by gillkashdeep** [comment]
[ADD] covid data as per province and weather is shown as city.
