### ISSUE TITLE
#add Schedule 

### ISSUE THREAD

**Issue by gillkashdeep** [gillkashdeep/COMP313-002-TEAM6#4]

**Comment by manmeetkaur729** [comment]
kash about this i got an idea from internet..like if we dont want to go for pro level..it could be like example alarm

**Comment by manmeetkaur729** [comment]
means a person willingly set notification time and our system would notify as push message or notification

**Comment by gillkashdeep** [comment]
Yes @manmeetkaur729 
@coolgithub123  so what is your opinion?

**Comment by gillkashdeep** [comment]
Add the Schedule is done!
Next step to fetch the Schedule  can anyone do this?@coolgithub123
Final send reminder.

**Comment by manmeetkaur729** [comment]
@gillkashdeep  i m going to start testing on the add schedule task done by you

**Comment by gillkashdeep** [comment]
Fetch the Schedule is done!

**Comment by gillkashdeep** [comment]
Complete the add schedule!
