### ISSUE TITLE
Addition of city and temp- notification

### ISSUE THREAD

**Issue by gillkashdeep** [gillkashdeep/COMP313-002-TEAM6#6]
Completed! please test.

**Comment by manmeetkaur729** [comment]
me and raj would work kash u can assign to us

**Comment by haocencol** [comment]
@gillkashdeep Write either a full story description or the task.
Each Github issue should have at most one assignee so that responsibility is owned by one team member.
Allocate each Github issue to a Milestone (i.e., Iteration x).

**Comment by gillkashdeep** [comment]
Please complete the test asap and report me any bug fixes. So, I will close the issue.

**Comment by manmeetkaur729** [comment]
@gillkashdeep  testing is done.... it is showing temp and other details perfectly and notification on/off is also working correctly

**Comment by manmeetkaur729** [comment]
but i didnt get option to show task is completed @gillkashdeep  plz help
