### ISSUE TITLE
#unit Conversion 

### ISSUE THREAD

**Issue by gillkashdeep** [gillkashdeep/COMP313-002-TEAM6#7]
The Unit conversion for one view is completed. @BNJain  Please complete the remanings. Sample code is on github to complete the task

**Comment by divyathakkar1417** [comment]
There are 2 bugs on this feature.
1. When converted to Fahrenheit, only one value is converted.
2. On the settings page, when selected Celsius unit, it still converts to Fahrenheit. 
3. The app crashes if only the location is input and not the unit conversion.

**Comment by gillkashdeep** [comment]
Fixes for bug 3.
The function can be implemented onchange instead of onclick.

**Comment by manmeetkaur729** [comment]
@gillkashdeep i got message from sydney he want to help in this task he messaged me... plz assign him this task along with bhagyesh

**Comment by gillkashdeep** [comment]
Merge the code @coolgithub123 and I am going to close the issue.
